"""Integration tests for Weibo platform — real API calls with debug tokens.

Requires ``tests/weibo_debug_tokens.json`` (generated by ``trawler login --platform weibo``).
Skip all tests with: ``pytest -m "not integration"``
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

import pytest

from platforms.weibo.api import (
    _parse_mobile_post,
    _parse_pc_post,
    fetch_user_posts,
    fetch_user_posts_mobile,
    fetch_user_posts_pc,
)
from platforms.weibo.comments import fetch_weibo_comment_highlights
from shared.config import Config, load_config
from shared.http import close_session

logger = logging.getLogger(__name__)

pytestmark = pytest.mark.integration

TEST_USER_ID = "2803301701"


# ── Helpers ──────────────────────────────────────────────────


def _load_debug_tokens() -> dict | None:
    """Load debug tokens from tests/weibo_debug_tokens.json."""
    path = Path(__file__).parent / "weibo_debug_tokens.json"
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def _cookie_str(tokens: dict) -> str:
    """Build semicolon-delimited cookie string from tokens dict."""
    cookies = tokens.get("cookies", {})
    return "; ".join(f"{k}={v}" for k, v in cookies.items())


def _require_tokens():
    """Check if tokens are available; skip test if not."""
    tokens = _load_debug_tokens()
    if tokens is None:
        pytest.skip("No debug tokens found. Run: trawler login --platform weibo")
    cookie = _cookie_str(tokens)
    if not cookie or "SUB=" not in cookie:
        pytest.skip("Debug tokens missing SUB cookie. Re-run: trawler login --platform weibo")
    return tokens


def _require_config() -> Config:
    """Load config; skip if weibo not enabled or no cookie."""
    config = load_config("config.toml")
    if not config.weibo.enabled:
        pytest.skip("Weibo not enabled in config.toml")
    if not config.weibo.auth.cookie:
        pytest.skip("No weibo cookie in config.toml. Run: trawler login --platform weibo")
    return config


# ── Real API: fetch_user_posts_mobile ────────────────────────


class TestMobileAPI:
    @pytest.mark.asyncio
    async def test_fetch_posts_from_real_api(self):
        """Fetch posts from real Weibo mobile API."""
        tokens = _require_tokens()
        cookie = _cookie_str(tokens)

        posts = await fetch_user_posts_mobile(cookie, user_id=TEST_USER_ID, max_posts=5)

        assert isinstance(posts, list)
        assert len(posts) > 0, "No posts returned from mobile API"
        # Should contain mblog objects with id field
        for p in posts:
            assert isinstance(p, dict)
            assert "id" in p, f"Post missing id: {list(p.keys())[:5]}"
            assert p.get("text"), f"Post {p.get('id')} has empty text"
        await close_session()

    @pytest.mark.asyncio
    async def test_parse_mobile_posts(self):
        """Fetch and parse real mobile posts into WeiboPost."""
        tokens = _require_tokens()
        cookie = _cookie_str(tokens)

        posts_raw = await fetch_user_posts_mobile(cookie, user_id=TEST_USER_ID, max_posts=3)
        assert len(posts_raw) > 0, "No raw posts from mobile API"

        parsed_count = 0
        for raw in posts_raw:
            post = _parse_mobile_post(raw)
            if post:
                parsed_count += 1
                assert post.post_id, "Parsed post missing post_id"
                assert post.author, "Parsed post missing author"
                assert post.pubdate > 0, "Parsed post missing pubdate"
                assert post.clean_text, "Parsed post missing clean_text"

        assert parsed_count > 0, "No posts could be parsed"
        await close_session()

    @pytest.mark.asyncio
    async def test_fetch_user_posts_high_level(self):
        """Test fetch_user_posts high-level wrapper with real API."""
        tokens = _require_tokens()
        cookie = _cookie_str(tokens)

        posts = await fetch_user_posts(cookie, user_id=TEST_USER_ID, max_posts=5)

        assert isinstance(posts, list)
        assert len(posts) > 0, "No posts returned from high-level API"
        for p in posts:
            assert p.post_id
            assert p.author
            assert p.pubdate > 0
        await close_session()


# ── Real API: fetch_user_posts_pc ────────────────────────────


class TestPCAPI:
    @pytest.mark.asyncio
    async def test_fetch_posts_from_real_pc_api(self):
        """Fetch posts from real Weibo PC API."""
        tokens = _require_tokens()
        cookie = _cookie_str(tokens)

        posts = await fetch_user_posts_pc(cookie, user_id=TEST_USER_ID, max_posts=5)

        assert isinstance(posts, list)
        if len(posts) > 0:
            for p in posts:
                assert isinstance(p, dict)
                assert "idstr" in p or "id" in p
        await close_session()

    @pytest.mark.asyncio
    async def test_parse_pc_posts(self):
        """Fetch and parse real PC posts into WeiboPost."""
        tokens = _require_tokens()
        cookie = _cookie_str(tokens)

        posts_raw = await fetch_user_posts_pc(cookie, user_id=TEST_USER_ID, max_posts=3)
        if not posts_raw:
            pytest.skip("No posts from PC API (may require different cookie)")

        parsed_count = 0
        for raw in posts_raw:
            post = _parse_pc_post(raw)
            if post:
                parsed_count += 1
                assert post.post_id
                assert post.author
                assert post.pubdate > 0

        assert parsed_count > 0, "No PC posts could be parsed"
        await close_session()


# ── Real API: Comments ───────────────────────────────────────


class TestCommentsAPI:
    @pytest.mark.asyncio
    async def test_fetch_comment_highlights(self):
        """Fetch real comment highlights for a known post."""
        tokens = _require_tokens()
        cookie = _cookie_str(tokens)

        # First get a post ID from mobile API
        posts = await fetch_user_posts_mobile(cookie, user_id=TEST_USER_ID, max_posts=1)
        if not posts:
            pytest.skip("No posts available to test comments")

        post_id = str(posts[0]["id"])
        config = _require_config()

        highlights = await fetch_weibo_comment_highlights(post_id, config)

        assert isinstance(highlights, list)
        if highlights:
            for h in highlights:
                assert h.content, "Comment has empty content"
                assert h.like_count >= 0, "Comment has negative like_count"
        await close_session()

    @pytest.mark.asyncio
    async def test_parse_real_comments(self):
        """Parse real comment data through _parse_comment."""
        tokens = _require_tokens()
        cookie = _cookie_str(tokens)

        # Get a post ID
        posts = await fetch_user_posts_mobile(cookie, user_id=TEST_USER_ID, max_posts=1)
        if not posts:
            pytest.skip("No posts available")

        post_id = str(posts[0]["id"])
        config = _require_config()
        highlights = await fetch_weibo_comment_highlights(post_id, config)

        # Highlight objects should already be parsed and valid
        assert all(isinstance(h.content, str) for h in highlights)
        assert all(isinstance(h.like_count, int) for h in highlights)
        await close_session()


# ── Config loading ───────────────────────────────────────────


class TestConfigIntegration:
    def test_config_loads_weibo_section(self):
        config = _require_config()
        assert config.weibo.enabled is True
        assert config.weibo.auth.cookie
        assert len(config.weibo.subscriptions) > 0
        assert config.weibo.subscriptions[0].user_id == "2803301701"


# ── Debug tokens sanity ──────────────────────────────────────


class TestDebugTokens:
    def test_debug_tokens_file_valid(self):
        tokens = _require_tokens()
        assert tokens["platform"] == "weibo"
        assert tokens["cookies"].get("SUB"), "Missing SUB cookie"
        assert tokens["expires_at"] > tokens["obtained_at"], "expires_at should be after obtained_at"
        assert tokens["cookies"].get("SUBP"), "Missing SUBP cookie"
